stages:
  download_dataset:
    cmd: python scripts/download.py hydra.run.dir="data" &>logs/download.out
    deps:
      - scripts/download.py
    outs:
      - logs/download.out
      -  ${root_dir}/${sub_dir}

  preprocess:
    cmd: python scripts/preprocess.py  &> logs/preprocess.out
    deps:
      - scripts/preprocess.py
      - ${root_dir}/${sub_dir}
    outs:
      - logs/preprocess.out
      - ${root_dir}/${split.dir}/${split.train}
      - ${root_dir}/${split.dir}/${split.val}
      - ${root_dir}/${split.dir}/${split.test}

#  train: 
#    cmd: python scripts/train.py trainer.epochs=2  hydra.run.dir="metrics"
#    deps: 
#      - scripts/train.py
#      - ${root_dir}/${split.dir}/${split.train}
#      - ${root_dir}/${split.dir}/${split.val}
#    
#    outs:
#      - ${root_dir}/${model.dir}/best_weights.h5
#      - ${root_dir}/${model.dir}/model

  train:
    cmd: python scripts/train2.py 
    deps:
      - scripts/train2.py
      - ${root_dir}/${split.dir}/train
      - ${root_dir}/${split.dir}/val
    params:
      - train
    outs:
      - ${root_dir}/${model.dir}/best_weights.h5
      - ${root_dir}/${model.dir}/model
      
    live:
      ${root_dir}/${model.dir}/training_metrics:
        summary: true
        html: true   

  evaluate:
    cmd: python scripts/eval.py 
    deps:
      - scripts/eval.py
      - ${root_dir}/${model.dir}/model
      - ${root_dir}/${split.dir}/${split.test}
    metrics:
    - ${root_dir}/${valid.dir}/metrics.json:
        cache: false
    plots:
    - ${root_dir}/${valid.dir}/predictions.csv:
        template: confusion
        x: true_label
        y: predicted_label
        title: confusion matrix
      
    - ${root_dir}/${valid.dir}/prc.json:
        cache: false
        x: recall
        y: precision

    - ${root_dir}/${valid.dir}/roc.json:
        cache: false
        x: fpr
        y: tpr


        
      
