wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.2
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1633072166
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 3
      - 8
      - 16
      4: 3.8.11
      5: 0.12.2
      8:
      - 5
base_filters:
  desc: null
  value: 26
epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.03371762691562857
